### ISSUE TITLE
`Alt+Tab` not works for VMware

### ISSUE THREAD

**Issue by MrBeanCpp** [sigoden/window-switcher#138]
When I start the virtual machine and the focus is on the `VMware` **title bar** (NOT inside the virtual machine), the `Alt+Tab` hook doesn't work, and the Windows default switcher pops up. 

However, when I shutdown the inner virtual machine, everything works under the same focus condition. 

I suspect that the virtual machine might have some impact on the Hook.

PS: I've ran `window-switcher` as Administrator.

**Comment by sigoden** [comment]
First, thank you for your feedback.

I have never used VMware, so I can't confirm the issue you're mentioning.

Since the window-switcher is not an integrated system application, and considering its working mechanism (keyboard hook), it may have failed to compete with VMware.

Sorry, there is currently no solution to this issue.
