### ISSUE TITLE
Some apps display the icons tiny

### ISSUE THREAD

**Issue by UrbanBreznik** [sigoden/window-switcher#143]
In my case, the app "Files" and photo album creation tool "Hofmann" are displaying the icons tiny. 
<img width="960" alt="Ph6EPFvPo7" src="https://github.com/user-attachments/assets/2f49a77e-5cdc-4e1e-a411-cb304f1bc8c9">

Not sure if this is a fault at their end or in the switcher.

https://files.community/
https://www.hofmann.es/album-de-fotos/crear/editor

**Comment by ian-h-chamberlain** [comment]
FWIW, I noticed this with Windows 10's builtin help viewer [`hh.exe`](https://learn.microsoft.com/en-us/previous-versions/windows/desktop/htmlhelp/about-the-html-help-executable-program), which many apps (e.g. 7-zip, AutoHotKey) use to display their help files.

It probably wouldn't look very nice, but maybe it would be possible just to upscale icons of this smaller size instead of just drawing them at their original size?

Also not sure if it's relevant, but I am using a high-DPI display with scaling set to 175% (although I see the same behavior on a regular display with 100% scale).
