### ISSUE TITLE
Please support the reverse order switching function.

### ISSUE THREAD

**Issue by hzh-test** [sigoden/window-switcher#43]
like Alt+Tab and Alt+Shift+Tab. 
Alt+~ and Alt+Shift+~

**Comment by sigoden** [comment]
You can easily switch to any program with only two shortcut keys.

If you feel the need for more, perhaps the butilin `alt+tab` or `win+tab is more suitable for you.

**Comment by sigoden** [comment]
`alt + tab` to find applications, ``` alt + ` ``` to find application windows.

`alt+tab`/``` alt+` ``` both support switching to the previous working window when triggered.

There are usually no more than 5 windows of the same application, and it is not annoying to switch one round.

If there are too many windows in the same application, you may need other window switching solutions.

**Comment by hzh-test** [comment]
You may have misunderstood my meaning.

**Comment by hzh-test** [comment]
I'll give an example. I have four windows: A, B, C, and D. The A window is currently in the front, and I want to switch to the B window. So I press Alt+`,. If I want to switch back to A, I have to press Alt+` three times, because it switches in order. So if there was an Alt+Shift+` to go back, I would only have to press Alt+Shift+` once. Ctrl+Tab and Ctrl+Shift+Tab work the same way. By the way, this is how Mac is designed. I have to use Windows for work reasons right now, so I really want to simulate the way Mac works.

**Comment by sigoden** [comment]
four windows: A, B, C, and D. The A window is currently in the front, and if you want to switch to the B window. you press `Alt+,`. If you want to switch back to A, **you release both `Alt` and `,` key**, then press `Alt +,` again, you get window A.

**Comment by sigoden** [comment]
Hold `Alt` key, press `,` key to cycle switching windows.

Release `Alt` key, press `Alt+,` key again, will switch to previous window.

**Comment by hzh-test** [comment]
It' sounds good.

**Comment by hzh-test** [comment]
But I think it will be better if it can back to the last window in switch apps. Because the app is more then the windows from same app. So When I switch to the fifth apps, I probably miss it. So I have to switch again. I have to carefully switch apps to avoid it. And if it can move back like press Shift key at the same time, I can switch app faster and don't care about miss it because I can move back with Shift key and do not switch again.

**Comment by jmpadilla18** [comment]
Hello! I'm new here and I'm a little lost.

From what I understand, the magnificent application only supports a maximum of 5 windows of the same application, right?
In any case, is there any type of ordering? The problem I am presenting is the following, and that is why I indicate it here, I think it is the right place.

The way Windows alt+tab works is as follows:
I have windows [0] A, [1] B and [2] C, I go to window [0] A and I execute alt+tab 2 times and I go to window [2] C, the current positions would be: [0] C, [1] A, [2] B

Is it the same in your application or what type of ordering do you use? For me it is necessary to know, because I use an order in the windows.

Thank you so much :)
