### ISSUE TITLE
Minimizing an application puts it at the end of the stack.

### ISSUE THREAD

**Issue by pushqrdx** [sigoden/window-switcher#62]
#### Current Behavior:
If you have notepad, browser, file explorer open in that order with your active application currently being notepad. if you minimize notepad so that your active application is now the browser, notepad will be moved to the end and next window will become file explorer instead.

#### Expected behavior:
Alt-tab after minimizing a window should bring back that window.

**Comment by sigoden** [comment]
I confirmed the problem. Thanks you.

windows-switcher just enum all windows and group them by application, then show the applicaitons in order.
The windows os puts the minimized window to the end, thus causing the application to appear at the end of the stack.

There's no way to handle this without listening to all window events and maintaining the window stack yourself, which isn't easy.

The problem is not serious and I'm not going to put a lot of effort into dealing with it.
