### ISSUE TITLE
Easy way to identify unwanted apps for blacklist

### ISSUE THREAD

**Issue by stianhoiland** [sigoden/window-switcher#83]
I gather that getting only the right things to show in the switcher (and not unwanted processes) isn't always so straightforward with the Windows API. It's nice to see that window-switcher has a manual blacklist for removing unwanted apps from the switcher.

But there is no easy way to get from "something is showing in the switcher that I would like to not show there" to actually putting the process name in the window-switcher.ini file. This is because it is not clear how window-switcher is internally identifying these unwanted apps. 

For example, on my computer an unwanted window-less process is showing up in window-switcher with a Nvidia icon. What do I do now? What is the window or process called? There are 10 running processes from Nvidia with several executable names on my computer. What if the icon is not recognizable, like a generic icon (Win32 for example)?

It would be nice to have an option (window-switcher.ini) to show the process and/or window name in the switcher for this purpose.

**Comment by sigoden** [comment]
Blacklist is an advanced feature. Used to avoid hotkey conflicts in some gaming applications.

A window always have a process, the process always have a exe path. It is most appropriate to use exe name identify the window. 

Technically, there is no window name, only window class, or window title, None of them are suitable for blacklist.

why not show process name in the window switcher? 

because process name is not same to app/product name, It will only cause misunderstanding. for example, a lot of people known vscode, but don't known the process name of vscode is `Code.exe`
