### ISSUE TITLE
Blacklist for alt-tab

### ISSUE THREAD

**Issue by DaNubCoding** [sigoden/window-switcher#89]
I have a custom bar program which is effectively a window, but is normally ignored when alt-tabbing. This program seems to recognize it as a window and includes it in the alt-tab. It would be great if there can be a blacklist for alt-tab as well.

**Comment by sigoden** [comment]
Does the window appear on the builtin alt-tab switcher? @DaNubCoding

If it is displayed, There is no need for special processing  because the window switcher is consistent with the built-in switcher.
If it doesn't show up, there's a bug with the window-switcher, please submit information about the program to help me fix it.

**Comment by DaNubCoding** [comment]
![image](https://github.com/sigoden/window-switcher/assets/75505891/1236cbf0-d87d-433f-a73f-9b2958b8f5e1)

![image](https://github.com/sigoden/window-switcher/assets/75505891/93dc38cb-ee94-4366-8ccd-2cc75aa127d1)

The program that is displayed as a blue circle is the bar window. The program is [GlazeWM](https://github.com/glzr-io/glazewm), its bar window doesn't appear on the built-in switcher, but does in this program.
