### ISSUE TITLE
Loosing focus after switching apps quicly

### ISSUE THREAD

**Issue by phcamargo23** [sigoden/window-switcher#93]
When switching a window, focus is lost.
From what you can see, it only happens that we change the window quickly. If you toggle smoothly, the focus remains, but if you do it quickly, it appears to trigger an automatic "alt" press, causing the focus to go to the toolbar.

https://github.com/sigoden/window-switcher/assets/5577637/3a3979af-5f90-4a43-ad95-e105cc1f83c4

My PC configurations is:
![image](https://github.com/sigoden/window-switcher/assets/5577637/99dfaa3c-c7b5-4d7e-80db-b15cd073fbe0)

My file configurations is:
```
a# Whether to show trayicon, yes/no
trayicon = yes 

[switch-windows]

# Hotkey to switch windows
hotkey = alt+`

# List of hotkey conflict apps
# e.g. game1.exe,game.exe
blacklist =

# Ignore minimal windows
ignore_minimal = no

[switch-apps]

# Whether to enable switching apps
enable = yes

# Hotkey to switch apps
hotkey = alt+tab

# Ignore minimal windows
ignore_minimal = no
```

**Comment by sigoden** [comment]
There is no way to solve this issue.

**Comment by stianhoiland** [comment]
This issue is certainly solvable. I got similar non-answers (#81, #82, #83), and, reading other issues, it seems to be a pattern with this developer. For a switcher without this issue, see [cmdtab](https://www.github.com/stianhoiland/cmdtab). I'm the author, after frankly being pissed by the responses I got here.

**Comment by sigoden** [comment]
This problem cannot be completely solved.

If you press the key too quickly, the keystrokes at a certain moment may be detect as two keyevents:  `alt+tab` and  `alt`

The `alt+tab` will switch to the next app, `alt` will activate menu, then a bug appeared.

I closed #81 #82 #83 because I didn't think it was necessary, This issue is closed because it cannot be resolved. This is no pattern.

If other people's open source projects cannot meet the demand, start a new project. I appreciate this behavior very much. I often do this myself.

**Comment by joelcho** [comment]
As sigoden mentioned, clicking the Alt key on Windows defaults to focusing on the Menu or Tool bar.

In fact, many people have been troubled by this and have provided some excellent solutions. Moreover, many excellent software programs allow you to modify this behavior in the preferences settings.
Please refer to the following link:

- For vscode [How to disable alt key to focus on File tab in VS code?](https://stackoverflow.com/questions/69869371/how-to-disable-alt-key-to-focus-on-file-tab-in-vs-code)

- For SublimeText [Disable ALT default key binding to toggle menu?](https://forum.sublimetext.com/t/disable-alt-default-key-binding-to-toggle-menu/61462)

Additionally, using AutoHotkey can globally block/change this behavior.

@phcamargo23

**Comment by stianhoiland** [comment]
Yeah; individually configure every app to workaround `window-switcher`'s limitations (and just live with the ones that can't be configured this way, like Chrome), or install a different app to perpetually run a script in the background to workaround `window-switcher`'s limitations...

Or use [cmdtab](https://www.github.com/stianhoiland/cmdtab) which *does the impossible /s* and doesn't have this issue.

Yeah, now I remember why I got so pissed by these inane responses and made my own.

**Comment by sigoden** [comment]
Your cmdtab don't have `alt` problem, but does have `tab` problem. 

Using delay and discarding `alt` key events did not completely solve the problem. @stianhoiland

**Comment by stianhoiland** [comment]
I don't know what you mean by "`tab` problem". Feel free to [create an issue](https://github.com/stianhoiland/cmdtab/issues/new)—I'm sure it can be fixed, and thus will be fixed.

And yes, the `alt` problem is solvable, as I've said and demonstrated. cmdtab's optional GUI delay has nothing to do with it. Correctly consuming and passing Alt key events is (and is part of a different approach to keyboard handling in cmdtab), as well as correctly using the SetForegroundWindow Alt key hack.

**Comment by sigoden** [comment]
Repeatedly pressing alt+tab to switch windows quickly as described in the issue，window-switcher capture additional `alt` keyevent (focus menu), cmdtab capture additional `tab` keyevent (insert tab).

**Comment by stianhoiland** [comment]
In [cmdtab](https://www.github.com/stianhoiland/cmdtab), repeatedly pressing Alt+Tab, Alt+Tab, Alt+Tab, or holding Alt and pressing Tab, Tab, Tab, does not produce any additional Tab key events (and doesn't insert any additional Tab in text fields nor selects next control).

Please [create an issue](https://github.com/stianhoiland/cmdtab/issues/new), preferably with evidence and steps to reproduce, like in this current issue. At this point I suspect you're just making shit up.

**Comment by sigoden** [comment]
See the video. Repeatedly pressing alt+tab to switch windows quickly.


https://github.com/sigoden/window-switcher/assets/4012553/99932282-3cff-41c8-b287-34f4ff329552

**Comment by stianhoiland** [comment]
You're fucking kidding me, right? I can *see* you being sloppy with pressing the keys, leading to you pressing Tab while you're not simultaneously holding Alt. To prove your bullshit I made a AutoHotkey script that spams Alt+Tab 100 times while [cmdtab](https://www.github.com/stianhoiland/cmdtab) is running and recorded it (video size reduced by frame dedup):

https://github.com/sigoden/window-switcher/assets/2081712/4246d218-f38d-47a3-bfac-8a9b715368d1

Not a single tab inserted. _And not a single additional Alt key event._

Why tf am I still here. Apparently I didn't properly learn my lesson the first time I interacted with you. Please refrain from anymore false comments about [cmdtab](https://www.github.com/stianhoiland/cmdtab).

**Comment by sigoden** [comment]
Why do you still not understand this issue? If you can keep `alt+tab` being triggered at the same time every time, there will be no problem at all.
Use two fingers to quickly press the `alt` key and the `tab` key. When the speed becomes faster, the key presses at a certain moment may be detected as two key press events: (`alt+tab`+`alt`), ( `alt+tab` + `tab`). That's why the error occurs. @stianhoiland
